# config.yaml

# YOLOv8 Segmentation Models
yolo:
  model_path: 'yolov8n-seg.pt'
  model_confidence: 0.4
  segmentation_confidence: 0.25

# DepthAnythingV2 Model
depth_model:
  # name: 'depth-anything/Depth-Anything-V2-Small-hf'
  name: 'Intel/dpt-swinv2-tiny-256'
  safe_distance_threshold: 150

# Firebase Configuration
firebase:
  cred_path: 'serviceAccountKey.json'
  db_url: 'https://firebot-sfy832-default-rtdb.asia-southeast1.firebasedatabase.app'
  command_path: '/firebot/command'

# Class IDs from your model
class_ids:
  fire: 80
  smoke: 81

# Instruction codes
commands:
  stop: 0
  forward: 1
  left: 2
  right: 3

# Frame division for decision making (thirds)
frame_division:
  left_end: 0.333
  right_start: 0.666

# Video Source
video_source: 0

# Command send interval in seconds
command_interval: 1.0